name: Go CI

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Verify dependencies
      run: go mod verify

    - name: Check formatting
      run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then echo "Format check failed"; exit 1; fi

    - name: Go Vet
      run: go vet ./...

    - name: Build
      run: go build -v ./cmd/proxy

    - name: Test
      run: go test -v ./...
